# Generated by Django 4.2.16 on 2026-06-23 12:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=255)),
                ('app_name', models.CharField(blank=True, max_length=255)),
                ('rule_type', models.CharField(choices=[('block', 'Fully Blocked'), ('limit', 'Daily Time Limit')], max_length=10)),
                ('daily_limit_minutes', models.PositiveIntegerField(blank=True, help_text='Only for LIMIT type', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['app_name'],
            },
        ),
        migrations.CreateModel(
            name='AppUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=255)),
                ('app_name', models.CharField(max_length=255)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(db_index=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-duration_seconds'],
            },
        ),
        migrations.CreateModel(
            name='PermissionAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('ACCESS_FINE_LOCATION', 'GPS Location'), ('CAMERA', 'Camera'), ('READ_CONTACTS', 'Contacts'), ('READ_PHONE_STATE', 'Phone State'), ('BIND_ACCESSIBILITY_SERVICE', 'Accessibility Service'), ('BIND_VPN_SERVICE', 'VPN Service')], max_length=50)),
                ('was_granted', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ScreenSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Расписание', max_length=100)),
                ('days_bitmask', models.PositiveIntegerField(default=127, help_text='Bitmask 1=Mon...64=Sun')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
