# Generated by Django 4.2.16 on 2026-06-23 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenschedule',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permissionalert',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appusage',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_usages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apprule',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apprule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='appusage',
            index=models.Index(fields=['child', '-date'], name='app_control_child_i_873e82_idx'),
        ),
        migrations.AddIndex(
            model_name='appusage',
            index=models.Index(fields=['package_name'], name='app_control_package_5606cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='appusage',
            unique_together={('child', 'package_name', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='apprule',
            unique_together={('child', 'package_name')},
        ),
    ]
