# Generated by Django 4.2.16 on 2026-06-23 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dns_filter', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnsquery',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dnscategory',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_categories', to='users.family'),
        ),
        migrations.AddField(
            model_name='blockeddomain',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_blocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blockeddomain',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_domains', to='users.family'),
        ),
        migrations.AddIndex(
            model_name='dnsquery',
            index=models.Index(fields=['child', '-timestamp'], name='dns_filter__child_i_f14e08_idx'),
        ),
        migrations.AddIndex(
            model_name='dnsquery',
            index=models.Index(fields=['child', 'was_blocked'], name='dns_filter__child_i_db8b46_idx'),
        ),
        migrations.AddIndex(
            model_name='blockeddomain',
            index=models.Index(fields=['family', 'domain'], name='dns_filter__family__371983_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='blockeddomain',
            unique_together={('domain', 'family')},
        ),
    ]
