# Generated by Django 4.2.16 on 2026-06-23 12:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SosEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sos_type', models.CharField(choices=[('alert', 'Alert (1-7 presses)'), ('emergency', 'Emergency (8+ presses)')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('notified', 'Family Notified'), ('emergency_sent', 'Emergency Services Notified'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('press_count', models.PositiveIntegerField(default=1)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('message', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SOS Event',
                'verbose_name_plural': 'SOS Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
