# Generated by Django 4.2.16 on 2026-06-23 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosevent',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sosevent',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_sos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sosevent',
            index=models.Index(fields=['child', '-created_at'], name='sos_soseven_child_i_2eca04_idx'),
        ),
        migrations.AddIndex(
            model_name='sosevent',
            index=models.Index(fields=['status'], name='sos_soseven_status_89e296_idx'),
        ),
    ]
