# Generated by Django 4.2.16 on 2026-06-23 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='geozoneevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='geozoneevent',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='location.geozone'),
        ),
        migrations.AddField(
            model_name='geozone',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_zones', to='users.family'),
        ),
        migrations.AddIndex(
            model_name='locationrecord',
            index=models.Index(fields=['user', '-recorded_at'], name='location_lo_user_id_ed501a_idx'),
        ),
        migrations.AddIndex(
            model_name='locationrecord',
            index=models.Index(fields=['user', 'timestamp'], name='location_lo_user_id_2f700a_idx'),
        ),
    ]
